version: "3.9"

services:
  backend:
    build: ./backend
    container_name: docintel_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - qdrant

  streamlit:
    build: ./backend
    container_name: docintel_streamlit
    command: streamlit run /app/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - ./backend/.env
    depends_on:
      - backend

  qdrant:
    image: qdrant/qdrant
    container_name: docintel_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
